export const SECTIONS_TITLES = [
    "INTRO",
    "VERSO",
    "VERSO 1",
    "VERSO 2",
    "VERSO 3",
    "VERSO 4",
    "PRE CORO",
    "PRE CORO 1",
    "PRE CORO 2",
    "CORO",
    "CORO 1",
    "CORO 2",
    "CORO 3",
    "CORO 4",
    "PUENTE",
    "PUENTE 1",
    "PUENTE 2",
    "PUENTE 3",
    "PUENTE 4",
    "INSTRUMENTAL",
    "SOLO",
    "EXHORTACIÓN",
    "FINAL"
]

export const CHORDS = [
    [
        "A",
        "A5",
        "A6",
        "A6/9",
        "A7",
        "A7(#9)",
        "A7(b5)",
        "A7(b9)",
        "A7sus4",
        "A9",
        "A11",
        "A13",
        "Aadd9",
        "Aaug",
        "Ab",
        "Ab5",
        "Ab6",
        "Ab6/9",
        "Ab7",
        "Ab7(#9)",
        "Ab7(b5)",
        "Ab7(b9)",
        "Ab7sus4",
        "Ab9",
        "Ab11",
        "Ab13",
        "Abadd9",
        "Abaug",
        "Abdim",
        "Abdim7",
        "Abm",
        "Abm6",
        "Abm7",
        "Abm7(b5)",
        "Abm9",
        "Abm11",
        "Abm13",
        "Abmaj7",
        "Abmaj9",
        "Abmaj11",
        "Abmaj13",
        "Absus2",
        "Absus4",
        "Adim",
        "Adim7",
        "Am",
        "Am6",
        "Am7",
        "Am7(b5)",
        "Am9",
        "Am11",
        "Am13",
        "Amaj7",
        "Amaj9",
        "Amaj11",
        "Amaj13",
        "Asus2",
        "Asus4",
    ],
    [
        "A#",
        "A#5",
        "A#6",
        "A#6/9",
        "A#7",
        "A#7(#9)",
        "A#7(b5)",
        "A#7(b9)",
        "A#7sus4",
        "A#9",
        "A#11",
        "A#13",
        "A#add9",
        "A#aug",
        "A#dim",
        "A#dim7",
        "A#m",
        "A#m6",
        "A#m7",
        "A#m7(b5)",
        "A#m9",
        "A#m11",
        "A#m13",
        "A#maj7",
        "A#maj9",
        "A#maj11",
        "A#maj13",
        "A#sus2",
        "A#sus4"
    ],
    [
        "B",
        "B5",
        "B6",
        "B6/9",
        "B7",
        "B7(#9)",
        "B7(b5)",
        "B7(b9)",
        "B7sus4",
        "B9",
        "B11",
        "B13",
        "Badd9",
        "Baug",
        "Bb",
        "Bb5",
        "Bb6",
        "Bb6/9",
        "Bb7",
        "Bb7(#9)",
        "Bb7(b5)",
        "Bb7(b9)",
        "Bb7sus4",
        "Bb9",
        "Bb11",
        "Bb13",
        "Bbadd9",
        "Bbaug",
        "Bbdim",
        "Bbdim7",
        "Bbm",
        "Bbm6",
        "Bbm7",
        "Bbm7(b5)",
        "Bbm9",
        "Bbm11",
        "Bbm13",
        "Bbmaj7",
        "Bbmaj9",
        "Bbmaj11",
        "Bbmaj13",
        "Bbsus2",
        "Bbsus4",
        "Bdim",
        "Bdim7",
        "Bm",
        "Bm6",
        "Bm7",
        "Bm7(b5)",
        "Bm9",
        "Bm11",
        "Bm13",
        "Bmaj7",
        "Bmaj9",
        "Bmaj11",
        "Bmaj13",
        "Bsus2",
        "Bsus4"
    ]
]

